name: Sync README and Deploy to Pages

on:
  push:
    branches:
      - master
    # paths:
    #   - 'README.md' 

jobs:
  permissions:
    issues: write
    pull-requests: write
  update-readme-on-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Checkout pages branch or create if not exists
      run: |
        git checkout pages || git checkout --orphan pages # 如果pages分支不存在，则创建新分支

    - name: Sync README.md to pages branch
      run: |
        git checkout master -- README.md
        cp README.md index.md # 复制README.md到index.md
        ls -l

    - name: Add, commit, and push to pages branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md index.md
        git commit -m "Sync README.md and update index.md on pages branch" --no-verify
        git push origin pages --no-verify
