name: Sync README and Deploy to Pages

on:
  push:
    branches:
      - master
    paths:
      - 'README.md' # 当README.md在master分支上被修改时触发

jobs:
  sync-readme-to-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Checkout pages
      run: |
        git checkout pages
        git checkout master -- README.md
        cp README.md index.md
        git add README.md index.md
        git commit -m "Sync README and Deploy to Pages" --no-verify
        git add index.md
        git commit -m "Update index.md on pages branch" --no-verify
        git push origin pages --no-verify
