name: Sync README and Deploy to Pages

on:
  push:
    branches:
      - master
    paths:
      - 'README.md' # 当README.md在master分支上被修改时触发

jobs:
  sync-readme-to-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Checkout master and pull latest README.md
      run: |
        git fetch origin master:master # 确保master分支是最新的

    - name: Checkout pages branch or create if not exists
      run: |
        git checkout pages || git checkout --orphan pages # 如果pages分支不存在，则创建新分支

    - name: Initialize README.md on pages branch if not exists
      run: |
        # 检查pages分支上是否存在README.md，如果不存在，则从master复制
        [ ! -f README.md ] && cp master/README.md ./ || echo "README.md already exists on pages branch"
        # 如果pages分支是新创建的（没有历史记录），则需要初始化提交
        [ ! "$(git rev-parse --is-empty HEAD)" ] || git add README.md && git commit -m "Initialize README.md on pages branch"

    - name: Copy README.md to index.md on pages branch
      run: |
        cp README.md index.md # 复制README.md到index.md

    - name: Commit and push to pages branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.md
        git commit -m "Sync README.md to index.md" -m "Update index.md from master branch"
        git push origin pages

    # 如果需要，这里可以添加部署到GitHub Pages的步骤
